---
- name: Instalacja forum phpBB3 (LAMP Stack)
  hosts: all
  become: yes

  tasks:
    - name: Aktualizacja cache i instalacja pakietów LAMP
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
          - php-xml
          - php-gd
          - php-mbstring
          - unzip
          - python3-mysqldb  # Dodatkowy pakiet potrzebny Ansible do rozmowy z MySQL
        state: present
        update_cache: yes

    - name: Utworzenie bazy danych MySQL
      mysql_db:
        name: phpbb_db
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name:
      mysql_user:
        name: forum_user
        password: "Haslo_Przykladowe_123!"
        priv: "phpbb_db.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name:
      mysql_user:
        name: Michal
        password: "Twoje_Haslo_1234"
        priv: "phpbb_db.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name:
      mysql_user:
        name: Patryk
        password: "123456"
        priv: "phpbb_db.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Pobranie plikow zrodlowych phpBB3
      command: wget https://download.phpbb.com/pub/release/3.3/3.3.11/phpBB-3.3.11.zip -O /tmp/phpbb.zip
      args:
        creates: /tmp/phpbb.zip

    - name: Rozpakowanie archiwum
      unarchive:
        src: /tmp/phpbb.zip
        dest: /home/azureuser/
        remote_src: yes

    - name: Przeniesienie plikow do katalogu serwera WWW
      command: cp -r /tmp/phpBB3 /var/www/html/
      args:
        creates: /var/www/html/phpBB3

    - name: Ustawienie uprawnien wlasnosci dla Apache
      file:
        path: /var/www/html/phpBB3
        owner: www-data
        group: www-data
        recurse: yes
